export const GET_ERRORS = 'GET_ERRORS';
export const CLIENT_LOADING = 'CLIENT_LOADING';

// User Types
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER ';

// Single Client Types
export const GET_CLIENT_PROFILE = 'GET_CLIENT_PROFILE';
export const CLIENT_NOT_FOUND = 'CLIENT_NOT_FOUND';

// ALL Clients Types
export const GET_ALL_CLIENTS_PROFILES = 'GET_ALL_CLIENTS_PROFILES';

// Social Render Types
export const GET_SOCIAL_RENDER = 'GET_SOCIAL_RENDER';
export const SOCIAL_RENDER_LOADING = 'SOCIAL_RENDER_LOADING';
export const SET_CONTENT_CALENDAR = 'SET_CONTENT_CALENDAR';
export const GET_CLIENT_CONTENT = 'GET_CLIENT_CONTENT';
